### ISSUE TITLE
TX_RET not matching Pano

### ISSUE THREAD

**Issue by kschlenker** [USAID-ICPI/OHA-Tableau-Dashboard-QA-QC#29]
TX_RET is not matching the Pano values for Uganda (nor can I replicate the tableau values using the genie extracts). Part of the problem is that the tab has not filtered for Results (it includes annual results, quarterly results, and targets). Not sure if there are other issues causing this as well (there also isn't a disag/standardized disagg filter applied but that may or may not be impacting things)

**Comment by jrose202** [comment]
I can change the target/results filter to only annual since it's only for FY17 and only affects this tab.  does that solve the issue?

**Comment by kschlenker** [comment]
That should solve the problem but it would be good to double check the final product against Pano for Uganda to make sure that the values are matching up and that there isn't something else also causing a problem

**Comment by jrose202** [comment]
I tried that and was still getting odd people reached numbers - different than Pano. 

% achieve was closer though

**Comment by kschlenker** [comment]
Does it have the N/D filter applied? And a standardized disagg filter applied? I think it should be filtering to include both Age Aggregated/Sex and Age/Sex (since at FY17 APR entering data in coarse & semi-fine should have been mutually exclusive this should be ok). 

TX_RET is a weird one in Pano depending on where you look. Because in some dashboards Pano has extra columns to display the other data elements that _should match the TX_RET N and D_ as a way to look at data quality (e.g., shows TX_NEW from prev year).
